### ISSUE TITLE
Asking for stories about Things or inanimate objects makes humans always appear in the story?

### ISSUE THREAD

**Issue by thadguidry** [stefanom/fably#1]
"Tell me a story about a squirrel"
"Tell me a story about a river rock"
"Tell me a story about a feather from a robin"

Somehow humans get introduced into the weaving threads of multiple stories.
Maybe I need to prompt with more or richer details about those things?

... a squirrel WHO could not find some nuts
... a river rock THAT tumbled down a waterfall
... a feather from a robin LOST to the wind in a canyon

Not sure how behind the scenes to make the stories more pure and imaginative without humans sometimes appearing.
Must I always additionally add

...without any humans in this story ?

Maybe a preference setting?

**Comment by stefanom** [comment]
Oh interesting. Have you tried modifying the prompt in fably/prompt.txt?

**Comment by thadguidry** [comment]
Bingo! Thanks!  I see now, you are using the user `query` WITH the system `prompt`.
https://github.com/stefanom/fably/blob/028449ee65eeab2c84551bafb48bbd66442ee6b2/fably/fably.py#L29-L32

So I can just modify the `prompt.txt`...which indeed seems to improve things!
Thanks Stefano!
